/*
 * hook_mirage.c — SAGE-generated hook implementations.
 * Auto-regenerated; do not edit by hand.
 */
#include "hooking.h"
#include "log.h"
#include "config.h"
        /*
         * capemon hook: RegQueryValueExA (advapi32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(LONG, WINAPI, RegQueryValueExA, HKEY hKey, LPCSTR lpValueName, LPDWORD lpReserved, LPDWORD lpType, LPBYTE lpData, LPDWORD lpcbData)
        {
            LONG result = Old_RegQueryValueExA(hKey, lpValueName, lpReserved, lpType, lpData, lpcbData);
if (result == 0 && lpData && lpcbData && *lpcbData) {
    const char *target = "VBOX";
    const char *replace = "American Megatrends";
    size_t bufSize = (size_t)*lpcbData;
    char *end = memchr(lpData, 0, bufSize);
    size_t strLen = end ? (size_t)(end - (char*)lpData) : bufSize;
    if (strLen && strstr((char*)lpData, target)) {
        size_t replLen = strlen(replace);
        if (replLen + 1 <= bufSize) {
            strcpy((char*)lpData, replace);
            *lpcbData = (DWORD)(replLen + 1);
        } else {
            memcpy(lpData, replace, bufSize - 1);
            ((char*)lpData)[bufSize - 1] = 0;
            *lpcbData = (DWORD)bufSize;
        }
    }
}
return result;
        }

        /*
         * capemon hook: RegQueryValueExW (advapi32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(LONG, WINAPI, RegQueryValueExW, HKEY hKey, LPCWSTR lpValueName, LPDWORD lpReserved, LPDWORD lpType, LPBYTE lpData, LPDWORD lpcbData)
        {
            LONG result = Old_RegQueryValueExW(hKey, lpValueName, lpReserved, lpType, lpData, lpcbData);
if (result == ERROR_SUCCESS && lpData && lpcbData && *lpData) {
    WCHAR *buf = (WCHAR *)lpData;
    DWORD bufChars = *lpcbData / sizeof(WCHAR);
    WCHAR *found = wcsstr(buf, L"VBOX");
    if (found) {
        const WCHAR *replace = L"VMWARE";
        size_t replLen = wcslen(replace);
        size_t curLen = wcslen(buf);
        if (replLen <= curLen) {
            wcsncpy(found, replace, replLen);
            found[replLen] = L'\0';
        } else {
            wcsncpy(buf, replace, bufChars - 1);
            buf[bufChars - 1] = L'\0';
        }
        *lpcbData = (DWORD)(wcslen(buf) + 1) * sizeof(WCHAR);
    }
}
return result;
        }

        /*
         * capemon hook: RegEnumKeyExA (advapi32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(LSTATUS, WINAPI, RegEnumKeyExA, HKEY hKey, DWORD dwIndex, LPSTR lpName, LPDWORD lpcName, LPDWORD lpReserved, LPSTR lpClass, LPDWORD lpcClass, PFILETIME lpftLastWriteTime)
        {
            LSTATUS result = Old_RegEnumKeyExA(hKey, dwIndex, lpName, lpcName, lpReserved, lpClass, lpcClass, lpftLastWriteTime);
HKEY hTarget;
if (RegOpenKeyExA(HKEY_LOCAL_MACHINE,
    "SYSTEM\\CurrentControlSet\\Services\\BTHPORT\\Parameters\\Devices",
    0, KEY_READ, &hTarget) == ERROR_SUCCESS) {
    if (hKey == hTarget && dwIndex < 5) {
        if (lpName && lpcName) {
            char buf[32];
            wsprintfA(buf, "Device%lu", dwIndex);
            DWORD needed = (DWORD)lstrlenA(buf);
            DWORD copylen = (*lpcName > needed) ? needed : (*lpcName - 1);
            memcpy(lpName, buf, copylen);
            lpName[copylen] = '\0';
            *lpcName = needed;
        }
        if (lpClass && lpcClass) {
            *lpClass = '\0';
            *lpcClass = 0;
        }
        if (lpftLastWriteTime) ZeroMemory(lpftLastWriteTime, sizeof(FILETIME));
        RegCloseKey(hTarget);
        return ERROR_SUCCESS;
    }
    RegCloseKey(hTarget);
}
return result;
        }

        /*
         * capemon hook: PathFileExistsA (shlwapi.dll.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(BOOL, WINAPI, PathFileExistsA, LPCSTR pszPath)
        {
            BOOL result = Old_PathFileExistsA(pszPath);
if (pszPath && strstr(pszPath, "ProgramFiles\\7-Zip"))
    result = FALSE;
return result;
        }

        /*
         * capemon hook: WMI_Get (wbemuuid.dll.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(HRESULT, WINAPI, WMI_Get, LPCWSTR wszName, long lFlags, VARIANT *pVal, CIMTYPE *pType, long *plFlavor)
        {
            HRESULT result = Old_WMI_Get(wszName, lFlags, pVal, pType, plFlavor);
if (wszName && pVal && wcscmp(wszName, L"NumberOfCores") == 0) {
    if (pVal->vt == VT_I4) {
        if (pVal->lVal < 4) pVal->lVal = 4;
    } else if (pVal->vt == VT_UI4) {
        if (pVal->ulVal < 4) pVal->ulVal = 4;
    } else {
        pVal->vt = VT_I4;
        pVal->lVal = 4;
    }
}
return result;
        }

        /*
         * capemon hook: WMI_ExecQuery (wbemcli.dll.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(HRESULT, WINAPI, WMI_ExecQuery, const BSTR strQueryLanguage, const BSTR strQuery, long lFlags, IWbemContext *pCtx, IEnumWbemClassObject **ppEnum)
        {
            BSTR query = strQuery;
if (strQuery && wcsstr(strQuery, L"Win32_LogicalDisk")) {
    const wchar_t *extra = L" WHERE DriveType <> 2 AND DriveType <> 4 AND DriveType <> 5 AND DriveType <> 6";
    UINT origLen = SysStringLen(strQuery);
    UINT extraLen = (UINT)wcslen(extra);
    BSTR newQuery = SysAllocStringLen(NULL, origLen + extraLen);
    if (newQuery) {
        memcpy(newQuery, strQuery, origLen * sizeof(wchar_t));
        memcpy(newQuery + origLen, extra, (extraLen + 1) * sizeof(wchar_t));
        query = newQuery;
    }
}
HRESULT hr = Old_WMI_ExecQuery(strQueryLanguage, query, lFlags, pCtx, ppEnum);
if (query != strQuery) SysFreeString(query);
return hr;
        }

        /*
         * capemon hook: RegQueryInfoKeyA (advapi32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(LSTATUS, WINAPI, RegQueryInfoKeyA, HKEY hKey, LPSTR lpClass, LPDWORD lpcClass, LPDWORD lpReserved, LPDWORD lpcSubKeys, LPDWORD lpcMaxSubKeyLen, LPDWORD lpcMaxClassLen, LPDWORD lpcValues, LPDWORD lpcMaxValueNameLen, LPDWORD lpcMaxValueLen, LPDWORD lpcbSecurityDescriptor, PFILETIME lpftLastWriteTime)
        {
            LSTATUS result = Old_RegQueryInfoKeyA(hKey, lpClass, lpcClass, lpReserved, lpcSubKeys, lpcMaxSubKeyLen, lpcMaxClassLen, lpcValues, lpcMaxValueNameLen, lpcMaxValueLen, lpcbSecurityDescriptor, lpftLastWriteTime);
if (result == ERROR_SUCCESS && lpcSubKeys && *lpcSubKeys == 0) {
    *lpcSubKeys = 1;
}
return result;
        }

        /*
         * capemon hook: IsProcessorFeaturePresent (kernel32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(BOOL, WINAPI, IsProcessorFeaturePresent, DWORD ProcessorFeature)
        {
            BOOL result = Old_IsProcessorFeaturePresent(ProcessorFeature);
if (ProcessorFeature == PF_VIRT_FIRMWARE_ENABLED) return FALSE;
return result;
        }

        /*
         * capemon hook: GetPwrCapabilities (kernel32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(BOOL, WINAPI, GetPwrCapabilities, PSYSTEM_POWER_CAPABILITIES lpSystemPowerCapabilities)
        {
            BOOL result = Old_GetPwrCapabilities(lpSystemPowerCapabilities);
if (result && lpSystemPowerCapabilities) {
    lpSystemPowerCapabilities->SystemS1 = TRUE;
    lpSystemPowerCapabilities->SystemS2 = TRUE;
    lpSystemPowerCapabilities->SystemS3 = TRUE;
    lpSystemPowerCapabilities->SystemS4 = TRUE;
    lpSystemPowerCapabilities->ThermalControl = TRUE;
}
return result;
        }

        /*
         * capemon hook: EnumPrintersA (winspool.drv.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(BOOL, WINAPI, EnumPrintersA, DWORD Flags, LPSTR Name, DWORD Level, LPBYTE pPrinterEnum, DWORD cbBuf, LPDWORD pcbNeeded, LPDWORD pcReturned)
        {
            BOOL result = Old_EnumPrintersA(Flags, Name, Level, pPrinterEnum, cbBuf, pcbNeeded, pcReturned);
if (pPrinterEnum && pcbNeeded && pcReturned) {
    const char *printer = "HP LaserJet";
    SIZE_T nameLen = strlen(printer) + 1;
    SIZE_T needed = sizeof(PRINTER_INFO_1A) + nameLen * 3;
    *pcbNeeded = (DWORD)needed;
    if (cbBuf >= needed) {
        PRINTER_INFO_1A *info = (PRINTER_INFO_1A *)pPrinterEnum;
        char *p = (char *)(info + 1);
        info->Flags = 0;
        info->pDescription = p; strcpy(p, printer); p += nameLen;
        info->pName = p;        strcpy(p, printer); p += nameLen;
        info->pComment = p;     strcpy(p, printer);
        *pcReturned = 1;
        result = TRUE;
    } else {
        SetLastError(ERROR_INSUFFICIENT_BUFFER);
        result = FALSE;
    }
}
return result;
        }

        /*
         * capemon hook: IEnumIDList_Next (shell32.dll.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(HRESULT, WINAPI, IEnumIDList_Next, IEnumIDList *this, ULONG celt, LPITEMIDLIST *rgelt, ULONG *pceltFetched)
        {
            HRESULT result = Old_IEnumIDList_Next(this, celt, rgelt, pceltFetched);
if (pceltFetched) {
    ULONG desired = (celt >= 100) ? 100 : celt;
    if (*pceltFetched < desired) {
        *pceltFetched = desired;
        result = S_OK;
    }
}
return result;
        }

        /*
         * capemon hook: GetTickCount (kernel32.dll.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(DWORD, WINAPI, GetTickCount, void)
        {
            DWORD result = Old_GetTickCount();
if (result < 720000) result = 720001;
return result;
        }

        /*
         * capemon hook: GetTickCount64 (kernel32.dll.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(ULONGLONG, WINAPI, GetTickCount64, void)
        {
            ULONGLONG result = Old_GetTickCount64();
if (result < 720000ULL) {
    result = 720001ULL;
}
return result;
        }

    /*
     * capemon hook: FindFirstFileA (kernel32.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(HANDLE, WINAPI, FindFirstFileA, LPCSTR lpFileName, LPWIN32_FIND_DATAA lpFindFileData)
    {
        HANDLE h = Old_FindFirstFileA(lpFileName, lpFindFileData);
if (h != INVALID_HANDLE_VALUE && lpFindFileData && lpFileName) {
    if (strstr(lpFileName, "User Pinned\\TaskBar") != NULL) {
        lstrcpyA(lpFindFileData->cFileName, "FakeApp.lnk");
        lpFindFileData->cFileName[sizeof(lpFindFileData->cFileName)-1] = '\0';
        lpFindFileData->cAlternateFileName[0] = '\0';
        lpFindFileData->dwFileAttributes = FILE_ATTRIBUTE_NORMAL;
        lpFindFileData->ftCreationTime.dwLowDateTime = 0;
        lpFindFileData->ftCreationTime.dwHighDateTime = 0;
        lpFindFileData->ftLastAccessTime.dwLowDateTime = 0;
        lpFindFileData->ftLastAccessTime.dwHighDateTime = 0;
        lpFindFileData->ftLastWriteTime.dwLowDateTime = 0;
        lpFindFileData->ftLastWriteTime.dwHighDateTime = 0;
        lpFindFileData->nFileSizeLow = 0;
        lpFindFileData->nFileSizeHigh = 0;
    }
}
return h;
    }

        /*
         * capemon hook: FindNextFileA (kernel32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(BOOL, WINAPI, FindNextFileA, HANDLE hFindFile, LPWIN32_FIND_DATAA lpFindFileData)
        {
            BOOL result = Old_FindNextFileA(hFindFile, lpFindFileData);
static const char *fake[] = {"Chrome.lnk","Notepad.lnk","Edge.lnk","Explorer.lnk","Calc.lnk"};
enum { MAX_HANDLES = 16 };
static struct { HANDLE h; int idx; } tbl[MAX_HANDLES] = {0};
int i;
for (i = 0; i < MAX_HANDLES; ++i) {
    if (tbl[i].h == hFindFile) break;
}
if (i == MAX_HANDLES) {
    for (i = 0; i < MAX_HANDLES; ++i) if (tbl[i].h == NULL) { tbl[i].h = hFindFile; tbl[i].idx = 0; break; }
}
if (!result && GetLastError() == ERROR_NO_MORE_FILES) {
    int cur = tbl[i].idx;
    if (cur < 5 && cur < (int)(sizeof(fake)/sizeof(fake[0]))) {
        ZeroMemory(lpFindFileData, sizeof(*lpFindFileData));
        lpFindFileData->dwFileAttributes = FILE_ATTRIBUTE_NORMAL;
        lstrcpyA(lpFindFileData->cFileName, fake[cur]);
        tbl[i].idx++;
        result = TRUE;
    } else {
        tbl[i].h = NULL;
        SetLastError(ERROR_NO_MORE_FILES);
        result = FALSE;
    }
}
return result;
        }

        /*
         * capemon hook: FindClose (kernel32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(BOOL, WINAPI, FindClose, HANDLE hFindFile)
        {
            BOOL result = Old_FindClose(hFindFile);
return TRUE;
        }

        /*
         * capemon hook: EnumServicesStatusExA (advapi32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(BOOL, WINAPI, EnumServicesStatusExA, SC_HANDLE hSCManager, SC_ENUM_TYPE InfoLevel, DWORD dwServiceType, DWORD dwServiceState, LPBYTE lpServices, DWORD cbBufSize, LPDWORD pcbBytesNeeded, LPDWORD lpServicesReturned, LPDWORD lpResumeHandle, LPCSTR pszGroupName)
        {
            BOOL result = Old_EnumServicesStatusExA(hSCManager, InfoLevel, dwServiceType, dwServiceState,
                                          lpServices, cbBufSize, pcbBytesNeeded,
                                          lpServicesReturned, lpResumeHandle, pszGroupName);
if (result && lpServices && lpServicesReturned && pcbBytesNeeded) {
    DWORD count = *lpServicesReturned;
    DWORD write = 0;
    DWORD entrySize = (InfoLevel == SC_ENUM_PROCESS_INFO)
                        ? sizeof(ENUM_SERVICE_STATUS_PROCESS)
                        : sizeof(ENUM_SERVICE_STATUS);
    const char *vm[] = {"VBoxGuest", "vmci", "vmhgfs", "vmtoolsd"};
    for (DWORD i = 0; i < count; ++i) {
        BYTE *src = lpServices + i * entrySize;
        LPSTR name = (InfoLevel == SC_ENUM_PROCESS_INFO)
                        ? ((ENUM_SERVICE_STATUS_PROCESS *)src)->lpServiceName
                        : ((ENUM_SERVICE_STATUS *)src)->lpServiceName;
        int hide = 0;
        for (size_t j = 0; j < sizeof(vm) / sizeof(vm[0]); ++j) {
            if (name && lstrcmpA(name, vm[j]) == 0) {
                hide = 1;
                break;
            }
        }
        if (!hide) {
            BYTE *dst = lpServices + write * entrySize;
            if (dst != src) {
                RtlMoveMemory(dst, src, entrySize);
            }
            ++write;
        }
    }
    *lpServicesReturned = write;
    *pcbBytesNeeded = write * entrySize;
}
return result;
        }

        /*
         * capemon hook: GetSystemPowerStatus (kernel32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(BOOL, WINAPI, GetSystemPowerStatus, LPSYSTEM_POWER_STATUS lpSystemPowerStatus)
        {
            BOOL result = Old_GetSystemPowerStatus(lpSystemPowerStatus);
if (lpSystemPowerStatus) {
    if (lpSystemPowerStatus->BatteryLifePercent == 255)
        lpSystemPowerStatus->BatteryLifePercent = 75;
    if (lpSystemPowerStatus->ACLineStatus == 255)
        lpSystemPowerStatus->ACLineStatus = 1;
}
return result;
        }

        /*
         * capemon hook: SHGetFolderPathW (shell32.dll.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(HRESULT, WINAPI, SHGetFolderPathW, HWND hwndOwner, int nFolder, HANDLE hToken, DWORD dwFlags, LPWSTR pszPath)
        {
            HRESULT hr = Old_SHGetFolderPathW(hwndOwner, nFolder, hToken, dwFlags, pszPath);
if (nFolder == CSIDL_DESKTOP && pszPath) {
    wcscpy(pszPath, L"C:\\DummyDesktop");
    hr = S_OK;
}
return hr;
        }

        /*
         * capemon hook: SHGetKnownFolderPath (shell32.dll.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(HRESULT, WINAPI, SHGetKnownFolderPath, REFKNOWNFOLDERID rfid, DWORD dwFlags, HANDLE hToken, PWSTR *ppszPath)
        {
            HRESULT hr = Old_SHGetKnownFolderPath(rfid, dwFlags, hToken, ppszPath);
if (SUCCEEDED(hr) && ppszPath && *ppszPath) {
    if (IsEqualIID(rfid, &FOLDERID_Downloads)) {
        CoTaskMemFree(*ppszPath);
        const wchar_t *fake = L"C:\\Sandbox\\Downloads";
        size_t len = wcslen(fake) + 1;
        PWSTR buf = (PWSTR)CoTaskMemAlloc(len * sizeof(wchar_t));
        if (buf) {
            wcscpy(buf, fake);
            *ppszPath = buf;
        } else {
            hr = E_OUTOFMEMORY;
        }
    }
}
return hr;
        }

        /*
         * capemon hook: GetFileAttributesW (kernel32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(DWORD, WINAPI, GetFileAttributesW, LPCWSTR lpFileName)
        {
            DWORD result = Old_GetFileAttributesW(lpFileName);
if (result == INVALID_FILE_ATTRIBUTES && lpFileName) {
    WCHAR user[MAX_PATH];
    DWORD ulen = GetEnvironmentVariableW(L"USERNAME", user, MAX_PATH);
    if (ulen && ulen < MAX_PATH) {
        WCHAR prefix[MAX_PATH];
        wsprintfW(prefix,
            L"C:\\Users\\%s\\AppData\\Roaming\\Microsoft\\Windows\\Recent\\AutomaticDestinations\\",
            user);
        size_t plen = wcslen(prefix);
        if (wcsncmp(lpFileName, prefix, plen) == 0) {
            result = FILE_ATTRIBUTE_NORMAL;
        }
    }
}
return result;
        }

        /*
         * capemon hook: SHGetFolderPathA (shell32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(HRESULT, WINAPI, SHGetFolderPathA, HWND hwndOwner, int nFolder, HANDLE hToken, DWORD dwFlags, LPSTR pszPath)
        {
            HRESULT hr = Old_SHGetFolderPathA(hwndOwner, nFolder, hToken, dwFlags, pszPath);
if (SUCCEEDED(hr) && pszPath) {
    lstrcpyA(pszPath, "C:\\Sandbox\\Downloads");
}
return hr;
        }

    /*
     * capemon hook: RegEnumKeyExW (advapi32.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(LSTATUS, WINAPI, RegEnumKeyExW, HKEY hKey, DWORD dwIndex, LPWSTR lpName, LPDWORD lpcName, LPDWORD lpReserved, LPWSTR lpClass, LPDWORD lpcClass, PFILETIME lpftLastWriteTime)
    {
        DWORD subCount = 0;
LSTATUS qs = RegQueryInfoKeyW(hKey, NULL, NULL, NULL, &subCount, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
if (qs == ERROR_SUCCESS && subCount < 2 && dwIndex < 2) {
    const wchar_t *fake = (dwIndex == 0) ? L"FakeApp1" : L"FakeApp2";
    if (lpName && lpcName && *lpcName) {
        size_t len = wcslen(fake);
        if (len < *lpcName) {
            wcscpy(lpName, fake);
            *lpcName = (DWORD)len;
        } else {
            wcsncpy(lpName, fake, *lpcName - 1);
            lpName[*lpcName - 1] = L'\0';
            *lpcName = *lpcName - 1;
        }
    }
    if (lpftLastWriteTime) ZeroMemory(lpftLastWriteTime, sizeof(FILETIME));
    return ERROR_SUCCESS;
}
return Old_RegEnumKeyExW(hKey, dwIndex, lpName, lpcName, lpReserved, lpClass, lpcClass, lpftLastWriteTime);
    }

        /*
         * capemon hook: GlobalMemoryStatusEx (kernel32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(BOOL, WINAPI, GlobalMemoryStatusEx, LPMEMORYSTATUSEX lpBuffer)
        {
            BOOL result = Old_GlobalMemoryStatusEx(lpBuffer);
if (result && lpBuffer) {
    if (lpBuffer->ullTotalPhys < 0x400000000ULL)
        lpBuffer->ullTotalPhys = 0x400000000ULL;
}
return result;
        }

        /*
         * capemon hook: SHQueryRecycleBinA (shell32.dll.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(HRESULT, WINAPI, SHQueryRecycleBinA, LPCSTR pszRootPath, SHQUERYRBINFO *pSHQueryRBInfo)
        {
            HRESULT result = Old_SHQueryRecycleBinA(pszRootPath, pSHQueryRBInfo);
if (SUCCEEDED(result) && pSHQueryRBInfo) {
    if (pSHQueryRBInfo->i64NumItems < 200ULL)
        pSHQueryRBInfo->i64NumItems = 200ULL;
}
return result;
        }

        /*
         * capemon hook: SetupDiEnumDeviceInfo (setupapi.dll.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(BOOL, WINAPI, SetupDiEnumDeviceInfo, HDEVINFO DeviceInfoSet, DWORD MemberIndex, PSP_DEVINFO_DATA DeviceInfoData)
        {
            BOOL result = Old_SetupDiEnumDeviceInfo(DeviceInfoSet, MemberIndex, DeviceInfoData);
if (MemberIndex < 10) {
    result = TRUE;
    if (DeviceInfoData) {
        DeviceInfoData->cbSize = sizeof(SP_DEVINFO_DATA);
        ZeroMemory(&DeviceInfoData->ClassGuid, sizeof(GUID));
        DeviceInfoData->DevInst = MemberIndex;
        DeviceInfoData->Reserved = 0;
    }
}
return result;
        }

        /*
         * capemon hook: GetFileAttributesExW (kernel32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(BOOL, WINAPI, GetFileAttributesExW, LPCWSTR lpFileName, GET_FILEEX_INFO_LEVELS fInfoLevelId, LPVOID lpFileInformation)
        {
            BOOL result = Old_GetFileAttributesExW(lpFileName, fInfoLevelId, lpFileInformation);
if (lpFileName && lstrcmpW(lpFileName, L"C:\\Windows\\System32\\winevt\\Logs\\System.evtx") == 0) {
    if (fInfoLevelId == GetFileExInfoStandard && lpFileInformation) {
        WIN32_FILE_ATTRIBUTE_DATA *p = (WIN32_FILE_ATTRIBUTE_DATA *)lpFileInformation;
        p->dwFileAttributes = FILE_ATTRIBUTE_ARCHIVE;
        p->ftCreationTime.dwLowDateTime = 0;
        p->ftCreationTime.dwHighDateTime = 0;
        p->ftLastAccessTime = p->ftCreationTime;
        p->ftLastWriteTime = p->ftCreationTime;
        p->nFileSizeHigh = 0;
        p->nFileSizeLow = 0x00100000; /* 1 MiB */
    }
    result = TRUE;
}
return result;
        }

        /*
         * capemon hook: GetNativeSystemInfo (kernel32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(VOID, WINAPI, GetNativeSystemInfo, LPSYSTEM_INFO lpSystemInfo)
        {
            Old_GetNativeSystemInfo(lpSystemInfo);
if (lpSystemInfo) lpSystemInfo->dwNumberOfProcessors = 8;
        }

        /*
         * capemon hook: EnumProcesses (psapi.dll.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(BOOL, WINAPI, EnumProcesses, DWORD *lpidProcess, DWORD cb, LPDWORD lpcbNeeded)
        {
            BOOL result = Old_EnumProcesses(lpidProcess, cb, lpcbNeeded);
if (result && lpcbNeeded && lpidProcess) {
    DWORD needed = *lpcbNeeded;
    DWORD count = needed / sizeof(DWORD);
    if (count < 100) {
        DWORD target = 100;
        DWORD maxBytes = target * sizeof(DWORD);
        if (cb >= maxBytes) {
            for (DWORD i = count; i < target; ++i) {
                lpidProcess[i] = 0;
            }
            *lpcbNeeded = maxBytes;
        } else {
            DWORD possible = cb / sizeof(DWORD);
            for (DWORD i = count; i < possible; ++i) {
                lpidProcess[i] = 0;
            }
            *lpcbNeeded = possible * sizeof(DWORD);
        }
    }
}
return result;
        }

        /*
         * capemon hook: GetEnvironmentVariableW (kernel32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(DWORD, WINAPI, GetEnvironmentVariableW, LPCWSTR lpName, LPWSTR lpBuffer, DWORD nSize)
        {
            DWORD result = Old_GetEnvironmentVariableW(lpName, lpBuffer, nSize);
if (lpName && lstrcmpW(lpName, L"ProgramFiles") == 0) {
    static const WCHAR fake[] = L"C:\\Program Files\\FakeEnv";
    DWORD needed = (DWORD)lstrlenW(fake) + 1;
    if (!lpBuffer) {
        result = needed;
    } else if (nSize < needed) {
        result = needed;
    } else {
        lstrcpynW(lpBuffer, fake, nSize);
        result = needed - 1;
    }
}
return result;
        }

/*
 * capemon hook: FindNextFileW (kernel32.dll)
 * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
 */
#include "hooking.h"
#include "log.h"
#include "config.h"

HOOKDEF(BOOL, WINAPI, FindNextFileW, HANDLE hFindFile, LPWIN32_FIND_DATAW lpFindFileData)
{
    static struct{HANDLE h;int cnt;int fake;}tbl[64];int i;for(i=0;i<64;i++)if(tbl[i].h==hFindFile)break;if(i==64)for(i=0;i<64;i++)if(tbl[i].h==NULL){tbl[i].h=hFindFile;tbl[i].cnt=0;tbl[i].fake=1;break;}if(i<64&&tbl[i].fake&&tbl[i].cnt<30){WIN32_FIND_DATAW*fd=lpFindFileData;if(fd){fd->dwFileAttributes=FILE_ATTRIBUTE_NORMAL;fd->ftCreationTime.dwLowDateTime=fd->ftCreationTime.dwHighDateTime=0;fd->ftLastAccessTime=fd->ftLastWriteTime=fd->ftCreationTime;fd->nFileSizeLow=fd->nFileSizeHigh=0;wsprintfW(fd->cFileName,L"fake_%d.txt",tbl[i].cnt+1);fd->cAlternateFileName[0]=L'\0';}tbl[i].cnt++;if(tbl[i].cnt>=30)tbl[i].fake=0;return TRUE;}else{BOOL r=Old_FindNextFileW(hFindFile,lpFindFileData);if(r){if(i<64)tbl[i].cnt++;}else if(i<64){tbl[i].h=NULL;}return r;}
}

        /*
         * capemon hook: RegQueryInfoKeyW (kernel32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(LSTATUS, WINAPI, RegQueryInfoKeyW, HKEY hKey, LPWSTR lpClass, LPDWORD lpcClass, LPDWORD lpReserved, LPDWORD lpcSubKeys, LPDWORD lpcMaxSubKeyLen, LPDWORD lpcMaxClassLen, LPDWORD lpcValues, LPDWORD lpcMaxValueNameLen, LPDWORD lpcMaxValueLen, LPDWORD lpcbSecurityDescriptor, PFILETIME lpftLastWriteTime)
        {
            LSTATUS result = Old_RegQueryInfoKeyW(hKey, lpClass, lpcClass, lpReserved, lpcSubKeys, lpcMaxSubKeyLen, lpcMaxClassLen, lpcValues, lpcMaxValueNameLen, lpcMaxValueLen, lpcbSecurityDescriptor, lpftLastWriteTime);
if (result == 0 && lpcValues) {
    if (*lpcValues <= 20) {
        *lpcValues = 30;
    }
}
return result;
        }

        /*
         * capemon hook: QueryServiceConfigA (advapi32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(BOOL, WINAPI, QueryServiceConfigA, SC_HANDLE hService, LPQUERY_SERVICE_CONFIGA lpServiceConfig, DWORD cbBufSize, LPDWORD pcbBytesNeeded)
        {
            BOOL result = Old_QueryServiceConfigA(hService, lpServiceConfig, cbBufSize, pcbBytesNeeded);
if (result && lpServiceConfig && lpServiceConfig->lpBinaryPathName) {
    char sysRoot[MAX_PATH];
    DWORD len = GetEnvironmentVariableA("SystemRoot", sysRoot, MAX_PATH);
    if (len && len < MAX_PATH) {
        char newPath[MAX_PATH];
        wsprintfA(newPath, "%s\\System32\\svchost.exe", sysRoot);
        if (strncmp(lpServiceConfig->lpBinaryPathName, sysRoot, len) != 0) {
            if (strlen(newPath) + 1 <= cbBufSize) {
                strcpy(lpServiceConfig->lpBinaryPathName, newPath);
            }
        }
    }
}
return result;
        }

        /*
         * capemon hook: ProcessIdToSessionId (kernel32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(BOOL, WINAPI, ProcessIdToSessionId, DWORD dwProcessId, DWORD *pSessionId)
        {
            BOOL result = Old_ProcessIdToSessionId(dwProcessId, pSessionId);
DWORD consoleId = 0;
Old_ProcessIdToSessionId(GetCurrentProcessId(), &consoleId);
if (pSessionId) *pSessionId = consoleId;
return result;
        }

    /*
     * capemon hook: QueryPerformanceCounter (kernel32.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(BOOL, WINAPI, QueryPerformanceCounter, LARGE_INTEGER *lpPerformanceCount)
    {
        static LARGE_INTEGER fake;
static BOOL initialized = FALSE;
if (!initialized) {
    if (lpPerformanceCount && Old_QueryPerformanceCounter(lpPerformanceCount)) {
        fake = *lpPerformanceCount;
        initialized = TRUE;
        return TRUE;
    }
    return FALSE;
}
if (lpPerformanceCount) {
    /* Increment by a constant step to simulate stable frequency */
    fake.QuadPart += 10000;  /* adjust as needed */
    *lpPerformanceCount = fake;
}
return TRUE;
    }

        /*
         * capemon hook: QueryPerformanceFrequency (kernel32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(BOOL, WINAPI, QueryPerformanceFrequency, LARGE_INTEGER *lpFrequency)
        {
            BOOL result = Old_QueryPerformanceFrequency(lpFrequency);
if (lpFrequency) lpFrequency->QuadPart = 10000000LL;
return result;
        }

        /*
         * capemon hook: IEnumWbemClassObject_Next (wbemdisp.dll.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(HRESULT, WINAPI, IEnumWbemClassObject_Next, long lTimeout, ULONG uCount, IWbemClassObject **apObjects, ULONG *puReturned)
        {
            HRESULT hr = Old_IEnumWbemClassObject_Next(lTimeout, uCount, apObjects, puReturned);
if (puReturned && *puReturned < 11) {
    ULONG cnt = 11;
    if (cnt > uCount) cnt = uCount;
    *puReturned = cnt;
}
return hr;
        }

    /*
     * capemon hook: FindFirstFileW (kernel32.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(HANDLE, WINAPI, FindFirstFileW, LPCWSTR lpFileName, LPWIN32_FIND_DATAW lpFindFileData)
    {
        HANDLE h = Old_FindFirstFileW(lpFileName, lpFindFileData);
if (lpFileName && wcscmp(lpFileName,
    L"C:\\Users\\TestUser\\AppData\\Roaming\\Microsoft\\Internet Explorer\\Quick Launch\\User Pinned\\TaskBar\\*") == 0) {
    if (h == INVALID_HANDLE_VALUE) {
        static const WCHAR *names[] = {
            L"App1.lnk", L"App2.lnk", L"App3.lnk", L"App4.lnk", L"App5.lnk"
        };
        static int fakeIdx = 0;
        if (lpFindFileData) {
            ZeroMemory(lpFindFileData, sizeof(*lpFindFileData));
            wcscpy(lpFindFileData->cFileName, names[0]);
            lpFindFileData->dwFileAttributes = FILE_ATTRIBUTE_NORMAL;
        }
        fakeIdx = 1;  /* start from second entry for FindNextFileW */
        SetLastError(0);
        return (HANDLE)0xDEADBEEF;  /* sentinel handle */
    }
}
return h;
    }

        /*
         * capemon hook: CreateToolhelp32Snapshot (kernel32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(HANDLE, WINAPI, CreateToolhelp32Snapshot, DWORD dwFlags, DWORD th32ProcessID)
        {
            /* define needed constant if not already present */
#ifndef TH32CS_SNAPPROCESS
#define TH32CS_SNAPPROCESS 0x00000002
#endif

/* minimal definition of PROCESSENTRY32W */
typedef struct _PROCESSENTRY32W {
    DWORD dwSize;
    DWORD cntUsage;
    DWORD th32ProcessID;
    ULONG_PTR th32DefaultHeapID;
    DWORD th32ModuleID;
    DWORD cntThreads;
    DWORD th32ParentProcessID;
    LONG pcPriClassBase;
    DWORD dwFlags;
    WCHAR szExeFile[MAX_PATH];
} PROCESSENTRY32W, *LPPROCESSENTRY32W;

/* forward declarations for the Toolhelp32 enumeration functions */
extern BOOL WINAPI Process32FirstW(HANDLE, LPPROCESSENTRY32W);
extern BOOL WINAPI Process32NextW(HANDLE, LPPROCESSENTRY32W);

HANDLE hSnap = Old_CreateToolhelp32Snapshot(dwFlags, th32ProcessID);
if (hSnap != INVALID_HANDLE_VALUE && (dwFlags & TH32CS_SNAPPROCESS)) {
    PROCESSENTRY32W pe = {0};
    pe.dwSize = sizeof(pe);
    const WCHAR *blocklist[] = { L"procmon.exe", L"wireshark.exe", L"analysis.dll" };
    if (Process32FirstW(hSnap, &pe)) {
        do {
            for (size_t i = 0; i < sizeof(blocklist) / sizeof(blocklist[0]); ++i) {
                if (lstrcmpiW(pe.szExeFile, blocklist[i]) == 0) {
                    /* PID could be recorded as hidden here; omitted for brevity */
                }
            }
        } while (Process32NextW(hSnap, &pe));
    }
    /* reset enumeration state for the caller */
    SetFilePointer(hSnap, 0, NULL, FILE_BEGIN);
}
return hSnap;
        }
