name: MSBuild
on:
  push:
    branches: [ "MIRAGE", "*-automated" ]
  pull_request:
    branches: [ "MIRAGE", "*-automated" ]
env:
  BUILD_CONFIGURATION: Release
  SOLUTION_FILE_PATH: capemon.sln
jobs:
  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86
            platform: Win32
          - arch: x64
            platform: x64
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: ${{ matrix.arch }}

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

    - name: Build
      run: msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ matrix.platform }} /p:PlatformToolset=v143 ${{ env.SOLUTION_FILE_PATH }}

    - uses: actions/upload-artifact@v4
      with:
        name: capemon_release_${{ matrix.arch }}
        path: |
          Release/capemon.dll
          x64/Release/capemon_x64.dll
        if-no-files-found: ignore

  publish:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - run: |
        echo "
        The rolling release triggered on \`${{ github.ref_name }}\`. [View run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})." > ${{ github.workspace }}-release-body.md

    - uses: actions/download-artifact@v4

    - uses: softprops/action-gh-release@v1
      with:
        tag_name: rolling
        files: |
          capemon_release_x86/Release/capemon.dll
          capemon_release_x64/x64/Release/capemon_x64.dll
        body_path: ${{ github.workspace }}-release-body.md

